# Julia Basics
In this notebook we are going to take a look at the very basics of Julia, learning the syntax and the very basics of the language. We'll take the perspective that most everyone is coming from Matlab. From Matlab, must of the functionality is quite similar! 

For full documentation about all the nuances of the Julia language, check out [the Julia Manual](http://julia.readthedocs.io/en/latest/manual).

## Running Julia Code
The Julia REPL is much like the one which you find in Matlab. You are able to run a single command at a time and look at a common workspace. This is a great way to tackle simple debugging or to do a simple computation. However, the most common way to interact through your experiments will be by running a Julia script file of some sort, denoted like by the `*.jl` extension. Given a Julia script, lets say, `foo.jl`, we can run this command from the terminal via

```bash
bash> julia foo.jl
```

Or we can run it from the REPL via

```bash
julia> include("foo.jl")
```

Note, here, the use of the function `include(...)`. This function will execute the contents of a script file within the current context of the REPL. Though, we must be careful if we are re-defining certain procedures. Depending on what our script does, sometimes running it twice in succession might result in undefined results due to redefinitions or overwritten variables.

```bash
julia> include("foo.jl")
(...some output...)
julia> include("foo.jl")
(...perhaps and error or unepxected output...)
```

Another way to interface with Julia is as we are doing here, through a Jupyter notebook.

-----

## Getting Help: Documentation
Another first thing to cover is how to find the information you need about specific functions. Most of the packages in Julia are well-documented. Of course, in fast-moving, new packages, there is often a lot of work to be done. However, all the core functionality has some good documentation. Lets say we want to know something about the fast Fourier transform (FFT). First, lets take a look at the documentaiton for the `apropos(...)` function. Note that if we want to know about a function, we just need to use the `?` prefix in the REPL.

In [4]:
?apropos   

search: apropos



```
apropos(string)
```

Search through all documentation for a string, ignoring case.


We can see that `apropos(...)` can be a very useful function if we are looking for a function that covers a certain topic, but we don't know exactly what function we're looking for. So, lets try to see if there is something using the Fourier transform.

In [7]:
apropos("prime")   # Note that strings in Julia are represented with double quotes! "..."

dct
idct
fft
primes
isprime
airybiprime
factor
airyaiprime
airyprime
primesmask


So, we see that there is one function which matches our query, lets check the documentation!

In [8]:
?factor

search: factor factorize factorial Factorization



```
factor(n) -> Dict
```

Compute the prime factorization of an integer `n`. Returns a dictionary. The keys of the dictionary correspond to the factors, and hence are of the same type as `n`. The value associated with each key indicates the number of times the factor appears in the factorization.

```jldoctest
julia> factor(100) # == 2*2*5*5
Dict{Int64,Int64} with 2 entries:
  2 => 2
  5 => 2
```


We can see that the doc-strings associated with `fft(...)` make use of both Markdown and TeX strings for a rich set of documentation!

------

## Installing Packages
Julia comes with a lot of features out of the box, but what makes it great is the huge community of programmers and researchers that are constantly adding packages to the Julia environment. Most are awesome, some are a bit mediocre and missing documentation. But often the first step when approaching any problem is to ask "has anyone already implemented this?" The answer is probably "yes". So make sure to exercise a bit of Google-fu before emparking.

Lets say that you really want to sample some random variables from a particular distribution, say, a Laplace distribution. You could charge ahead and re-write this procedure yourself, and possibly introduce a bug or two, or you could use the nice work done in [Distributions.jl](https://github.com/JuliaStats/Distributions.jl). 

So, lets say that you've decided that you want to use this package...what do you do? Well, you need to add it to your Julia environment. How can you do this? Most well-maintained Julia packages are listed on a public tracker, so to add a package we only need to make a very simple call from Julia. Specifically...

In [9]:
Pkg.add("Distributions")
using Distributions

INFO: Nothing to be done
INFO: METADATA is out-of-date — you may not have the latest version of Distributions
INFO: Use `Pkg.update()` to get the latest versions of your packages


The `Pkg.add()` command only needs to be run once, this function will download the package code to your machine. Subsequently, when you want to make use of the Distributions package, you need to call `using Distibutions`. This is the same for any external package you want to use with Julia.

Many packages also ship with a test-framework, this is best-practice. We can ensure that a package is working properly on our system by running its tests, if we are so inclined.

In [10]:
Pkg.test("Distributions")

INFO: Computing test dependencies for Distributions...
INFO: Installing ForwardDiff v0.1.8
INFO: Testing Distributions


Running tests:
	From worker 7:	    -----
	From worker 4:	    testing Distributions.CategoricalDirectSampler
	From worker 4:	    testing Distributions.AliasTable
	From worker 6:	    [Discrete]
	From worker 6:	    ------------
	From worker 4:	    testing Distributions.BinomialGeomSampler
	From worker 5:	    testing Distributions.Categorical(K=2, p=[0.5,0.5])
	From worker 4:	    testing Distributions.BinomialTPESampler
	From worker 3:	   testing PoissonBinomial p=0.8, n=6
	From worker 3:	   testing PoissonBinomial p=0.5, n=10
	From worker 3:	   testing PoissonBinomial p=0.04, n=20
	From worker 6:	    testing Bernoulli()
	From worker 3:	   testing PoissonBinomial [10 × 0.1, 10 × 0.5, 10 × 0.9]
	From worker 3:	   testing PoissonBinomial [1 × 0.99, 10 × 0.1, 100 × 0.05]
	From worker 3:	   testing PoissonBinomial [5 × 0.01, 1 × 0.99, 3 × 0.999]
	From worker 3:	   testing PoissonBinomial [10 × 0.0, 7 × 0.9, 10 × 0.5]
	From worker 5:	    testing Distributions.Categorical(K=4, p=[0.1,0.3,0.2,0.4

INFO: Distributions tests passed
INFO: Removing ForwardDiff v0.1.8


Finally, from time to time we need to make sure that all of our packages are up-to-date. Since Julia is a living ecosystem, it is important to update regularily.

In [3]:
Pkg.update()

INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove


---

## Variables & Types
In Julia, we have all of the common types of variables, from integers to symbols. Lets take a look at a few examples

In [25]:
# A 64-bit Integer value
x = 3       
println("x = $x is of type $(typeof(x)).")


x = 3 is of type Int64.


> *Notice the use of *`$(variable)`* inside of a string to insert varaibles!*

In [34]:
# A 64-bit Floating Point value
x = 2.7182818284590
println("x = $x is of type $(typeof(x)).")

x = 2.718281828459 is of type Float64.


In [43]:
# An ASCII String
x = "Hello World"
println("x = $x is of type $(typeof(x)).")

# A UTF String
x = "«École Normale Supérieure»  Ωç≈"
println("x = $x is of type $(typeof(x)).")

# A TeX String
using LaTeXStrings
x = L"\mathcal{Z} = \sum_{\mathb{s}} e^{\sum_{<i,j>} J_{ij} s_i s_j}"
println("x = $x is of type $(typeof(x)).")

x = Hello World is of type ASCIIString.
x = «École Normale Supérieure»  Ωç≈ is of type UTF8String.
x = $\mathcal{Z} = \sum_{\mathb{s}} e^{\sum_{<i,j>} J_{ij} s_i s_j}$ is of type LaTeXStrings.LaTeXString.


In [44]:
# A Symbol
x = :optionA
println("x = $x is of type $(typeof(x)).")

# Using a symbol
if x == :optionB
    println("Perform optionB.")
elseif x == :optionA
    println("Perform optionA.")
else
    println("Not an option!")
end

x = optionA is of type Symbol.
Perform optionA.


In [49]:
# A Dictionary
x = Dict(:optionA => "valueA", :optionB => "valueB")
println("x = $x is of type $(typeof(x)).")

# Referencing items in a dictionary
println(x[:optionA])
println(x[:optionB])
println(x[:unseenOption])

x = Dict(:optionB=>"valueB",:optionA=>"valueA") is of type Dict{Symbol,ASCIIString}.
valueA
valueB


LoadError: LoadError: KeyError: unseenOption not found
while loading In[49], in expression starting on line 8

In [51]:
x[:unseenOption] = "anotherValue"
dump(x)

Dict{Symbol,ASCIIString} len 3
  unseenOption: ASCIIString "anotherValue"
  optionB: ASCIIString "valueB"
  optionA: ASCIIString "valueA"


---

## Arrays and Lists
Lets do a few basic operations to see how Julia works with arrays.

In [65]:
A = [1 2 3 4 5]     # Define an Array, A
B = [1,2,3,4,5]     # Define an Array, B
A == B              # Are these the same array?

false

What happened, here? We thought that we have two arrays, each containing the same entries, but they don't evaluate as equal. Lets investigate a bit. Can we add these arrays together?

In [54]:
C = A + B

LoadError: LoadError: DimensionMismatch("dimensions must match")
while loading In[54], in expression starting on line 1

In fact, we cannot, even add these two arrays together. However, our error message gives us some information. It seems that we have a mismatch of dimensionality. But, why?

In [57]:
dump(A)
summary(A)

Array(Int64,(1,5)) 1x5 Array{Int64,2}:
 1  2  3  4  5


"1x5 Array{Int64,2}"

In [66]:
dump(B)

Array(Int64,(5,)) [1,2,3,4,5]


Now we see the issue. In our definition of `A`, we used spaces, while in our definition of `B` we use commas. By using spaces, we are forcing the entries to take new columns, making `A` a *two-dimensional array*. However, `B` remains a one dimensional array, or list, as we refer to items separated by commas. Hence the mismatch!

Lets say we are still intent on adding these two arrays together, and we know that the `A` has only one row. We can cast it as a vector to accomplish our desired operation.

In [79]:
@time C = vec(A) + B

  0.000004 seconds (7 allocations: 320 bytes)


5-element Array{Int64,1}:
  2
  4
  6
  8
 10

We can see that the resulting output is as a list, a one dimensional array. But what happens if we attempt to use the transpose operation, thinking that we can change the column-vector `A` to be compatible with the row-vector `B`?

In [16]:
C = A' + B

5x1 Array{Int64,2}:
  2
  4
  6
  8
 10

The result is indeed a row-vector, however, notice the difference in dimensionlaity. In this case, the result `C` is explicitly a *two-dimensional array*, which just happens to have a single column. So, we see that Julia will **promote** the type of `B` from a list to a two-dimensional array in order to accomplish the addition as all lists/vectors are assumed to be row-vectors.

Now, lets say we want to do something a little bit more interesting. One of the features of Julia is that it can handle operation **broadcasting** in a simple manner. We denote a broadcast by the `.` operator before the operation. Lets see what happens if we try to add our column and row vectors together...

In [72]:
@time C = A .+ B

  0.000021 seconds (22 allocations: 1.109 KB)


5x5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

This is an interesting result. We see that we get a full matrix of values. Why? When we broadcast an operation between a matrix and a vector, it will extend the vector out (via repetition) to math the dimension of the matrix. In this case, both vectors are extended out to fit the non-singleton dimension of the other. Subsequently, the addition operation is carried out. We could duplicate the same operation explicitly via...

In [73]:
@time C = repmat(A,5,1) + repmat(B,1,5)

  0.000008 seconds (30 allocations: 1.859 KB)


5x5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [74]:
?repmat

search: repmat



```
repmat(A, n, m)
```

Construct a matrix by repeating the given matrix `n` times in dimension 1 and `m` times in dimension 2.


Lets try some other ways of constructing `A` and `B`. We can also define *ranges* of variables. In this case, lets use the range `1:5`, which is understood as the range `1:1:5` by Julia, i.e., counting from 1 to 5, inclusively, by ones.

In [81]:
A = 1:5
@time C = A + B

  0.000003 seconds (6 allocations: 288 bytes)


5-element Array{Int64,1}:
  2
  4
  6
  8
 10

This is a valid addition operation, in our case. The range of `A` is interpreted as a vector, in this case, and added to `B`. What happens if `B` is also a list?

In [82]:
B = 1:5
C = A + B

2:2:10

We can see that instead of getting a vector, we get another range, taken as the addition of the elements of each of the individual ranges, e.g. `1+1:1+1:5+5`. Considering our previous result of `[2,4,6,8,10]`, we see that this range is still giving us an expected result, just in a different form. What if we wanted to read this as a vector?

In [83]:
collect(C)

5-element Array{Int64,1}:
  2
  4
  6
  8
 10

In [85]:
?collect

search: collect Collections



```
collect(collection)
```

Return an array of all items in a collection. For associative collections, returns Pair{KeyType, ValType}.

```
collect(element_type, collection)
```

Return an array of type `Array{element_type,1}` of all items in a collection.


---

## Comprehensions
We could also have defined our lists in another way, by comprehensions. For example...

In [86]:
A = [i for i in 1:5]
B = [i for i in 1:5]
dump(A)
dump(B)
C = A + B

Array(Int64,(5,)) [1,2,3,4,5]
Array(Int64,(5,)) [1,2,3,4,5]


5-element Array{Int64,1}:
  2
  4
  6
  8
 10

Comprehensions can be a powerful tool for short-form expressions. For instance...

In [87]:
A = [sin(i) for i in 0:0.1:2*pi]
B = [cos(i) for i in 0:0.1:2*pi]
dump(A)
dump(B)
C = A.^2 + B.^2      # Trig. Identity

Array(Float64,(63,)) [0.0,0.0998334,0.198669,0.29552,0.389418,0.479426,0.564642,0.644218,0.717356,0.783327  …  -0.832267,-0.772764,-0.70554,-0.631267,-0.550686,-0.464602,-0.373877,-0.279415,-0.182163,-0.0830894]
Array(Float64,(63,)) [1.0,0.995004,0.980067,0.955336,0.921061,0.877583,0.825336,0.764842,0.696707,0.62161  …  0.554374,0.634693,0.70867,0.775566,0.834713,0.88552,0.927478,0.96017,0.983268,0.996542]


63-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 ⋮  
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

Note here, that in order to accomplish the square operation per-element, we make use of the `.` operator again. At its root, in Julia, this operator signifies a per-element operation. However, Julia will *also* broadcast that opeartion when necessary.

In [88]:
?.^

search: .^



```
.^(x, y)
```

Element-wise exponentiation operator.


We can even construct multidimensional arrays through comprehensions, as well. Say we wanted to duplicate the earlier result of `C = A .+ B`, for instance.

In [89]:
C = [i+j for i in 1:5, j in 1:5]

5x5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

So, comprehensions seem pretty powerful, as compared to Matlab. But in the case of a multidimensional array, how are the dimensions proportioned? Lets use Tuples to see where, exactly, the entries of our solution go. Lets resize one of the dimensions so that we can tell them apart.

In [28]:
C = [(i,j) for i in 1:5, j in 1:3]

5x3 Array{Tuple{Int64,Int64},2}:
 (1,1)  (1,2)  (1,3)
 (2,1)  (2,2)  (2,3)
 (3,1)  (3,2)  (3,3)
 (4,1)  (4,2)  (4,3)
 (5,1)  (5,2)  (5,3)

We see that the dimensions are assigned in order of the definition in the comprehension, i.e. `i in 1:5` is interpreted as an index over rows (of which there will be 5) and `j in 1:3`, since it comes second, is interpreted as an index across columns (of which there will be 3), and so on. We can do the same for higher-dimensional tensors.

In [29]:
C = [(i,j,k) for i in 1:5, j in 1:3, k in 1:2]

5x3x2 Array{Tuple{Int64,Int64,Int64},3}:
[:, :, 1] =
 (1,1,1)  (1,2,1)  (1,3,1)
 (2,1,1)  (2,2,1)  (2,3,1)
 (3,1,1)  (3,2,1)  (3,3,1)
 (4,1,1)  (4,2,1)  (4,3,1)
 (5,1,1)  (5,2,1)  (5,3,1)

[:, :, 2] =
 (1,1,2)  (1,2,2)  (1,3,2)
 (2,1,2)  (2,2,2)  (2,3,2)
 (3,1,2)  (3,2,2)  (3,3,2)
 (4,1,2)  (4,2,2)  (4,3,2)
 (5,1,2)  (5,2,2)  (5,3,2)

Looking at the reported dimensionality of the tensor (`5x3x2`), we see that the dimension assignments match the order of our variabe definitions in the comprehension.

---

## Indexing
We now look to see how to accomplish array indexing. Arrays are indexed in much the same as in Matlab, except for the notation. In Julia, we use `[]` to index arrays instead of `()`. Otherwise, it is the same. For two dimensional arrays, the indexing is done by `[row,col]`.  

In [102]:
A = [1,2,3,4,5]
println(A .< 4)
println(find(A .< 4))

A[ 1:3 ]

Bool[true,true,true,false,false]
[1,2,3]


3-element Array{Int64,1}:
 1
 2
 3